theme: jekyll-theme-cayman
title: Sandai
description: Home Sweet Home

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

footer:
  links:
    - label: "(Home)"
      # icon: "fab fa-fw fa-twitter-square"
      url: "https://mettalik.github.io"
