theme: jekyll-theme-cayman
title: Sandai | Erwan
description: Home Sweet Home

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  
relative_links:
  enabled: true
  collections: true
