theme: jekyll-theme-cayman
title: Sandaidev
description: Home Sweet Home


baseurl: https://sandaidev.github.io

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  
relative_links:
  enabled: true
  collections: true
